import './global.css';

export const metadata = {
    title: 'Welcome to next',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="h-screen flex items-center justify-center">
                {children}
            </body>
        </html>
    );
}
